### ISSUE TITLE
Unsupported item key.

### ISSUE THREAD

**Issue by Cyphr00** [kvaps/zabbix-linux-container-template#12]
I imported the template, linked it to the host and put in /etc/zabbix/zabbix_agentd.d/ zabbix_container.conf .  Don't get any Data, just the Response: "Unsupported item key."

**Comment by Kornelius777** [comment]
Same here...

**Comment by yferszt** [comment]
On a debian lxc I solved this by placing the file -> `/etc/zabbix/zabbix_agentd.conf.d/zabbix_container.conf`
Restart the service `systemctl restart zabbix-agent`

**Comment by kvaps** [comment]
I don't use this script for many years, if you know how to fix it please send PR 
I'm going to accept it

**Comment by yferszt** [comment]
> I don't use this script for many years, if you know how to fix it please send PR I'm going to accept it

Done

**Comment by kvaps** [comment]
@yferszt accepted, thanks for contribution!
